### ISSUE TITLE
2020.02.04-08:00pm UTC-0 | next datdot sync

### ISSUE THREAD

**Issue by serapath** [datdotorg/website#27]
## `location` + [time zone converter](https://www.worldtimeserver.com/convert_time_in_UTC.aspx)
* https://talky.io/datdot
* https://gitter.im/playproject-io/community

| [**place:**][3] | Honolulu  | Vancouver | Ottawa   | Berlin      |    Taipei    | 
|-------------------:|--------------|----------------|-------------|-------------|---------------|
| **local time:** | `10:00am` |`12:00pm`|`15:00pm`|`9:00pm` |  `4:00am`  |

# AGENDA
1. What was done since last meeting?
  * @joshua-mir
    * [`datdot-research#9` 2020.01.?? | consult with mafintosh](https://github.com/playproject-io/datdot-research/issues/9)
    * [`datdot-substrate#1` roadmapping](https://github.com/playproject-io/datdot-substrate/issues/1)
    * [`datdot-research#6` user accounts + (API & UI)](https://github.com/playproject-io/datdot-research/issues/6)
    * [`datdot-research#7` substrate validator set & costs for submitting extrinsics](https://github.com/playproject-io/datdot-research/issues/7)
  * @ninabreznik
    * [`datdot-research#9` 2020.01.?? | consult with mafintosh](https://github.com/playproject-io/datdot-research/issues/9)
    * [`datdot-service#2` make lab environment to reliably test scenarios](https://github.com/playproject-io/datdot-service/issues/2)
    * [`datdot-service#1` roadmapping](https://github.com/playproject-io/datdot-service/issues/1)
    * [`datdot-research#3` research proof-of-service](https://github.com/playproject-io/datdot-research/issues/3)
  * @serapath
    * [`datdot-research#9` 2020.01.?? | consult with mafintosh](https://github.com/playproject-io/datdot-research/issues/9)
    * [`datdot#22` spec: make presentable spec after public w3f wave4 announcement](https://github.com/playproject-io/datdot/issues/22)
    * [`datdot-research#1` roadmapping](https://github.com/playproject-io/datdot-research/issues/1)
    * [`datdot#1` roadmapping](https://github.com/playproject-io/datdot/issues/1)
  * @fionataeyang 
    * [`brand#2` Ideas of interaction design collection](https://github.com/playproject-io/brand/issues/2)
    * [`datdot#2` datdot project landing page](https://github.com/playproject-io/datdot/issues/2)
  * @RangerMauve
    * [`datdot-research#9` 2020.01.?? | consult with mafintosh](https://github.com/playproject-io/datdot-research/issues/9)
    * [`datdot#24` encoding compatible hypercores](https://github.com/playproject-io/datdot/issues/24)
  * @substack
      * ???
2. [How do **roadmapping priorities** currently look like?][1]
3. [Create new meeting and plan what issues we will do until then][2]
    * => **[`2020.02.11-08:00pm UTC-0#28`next datdot sync](https://github.com/playproject-io/datdot/issues/28)**

[1]: https://github.com/playproject-io/datdot/issues/1
[2]: https://github.com/playproject-io/datdot/issues/new?template=event.md
[3]: https://timezoneninja.com/

# minutes
`no recordings`

**Comment by jam10o-new** [comment]
didn't catch y'all online if the call did happen - either way I guess I'll put a status update here and we can discuss it async, I guess:

 haven't committed anything this week and my next two days are pretty much blocked, but I did have some solidification re: attestations, shouldn't need much update to api, other than maybe adding additional parameters to register attestations (for specifying registration of friends, if we want them to participate onchain at all) [correction/edit: friends should only need to register if they need to be reported, I think that this would need an additional vec in the storage value I describe below] 

Weekend plans are figuring out if what Nina has been seeing is a bug - it's another off-by-one at worst - but in my ad-hoc testing in the apps UI I haven't been able to replicate it yet. After that is done, finishing off the hash types (blind until we have some reliable challenge response attempts, which is why I'm prioritizing the potential bug in challengeMap first), and then finally finishing off the first implementation of attestations.

Specifically: I have attestations as a tuple of two vecs which represent "required attestations" and "seen attestations". Anyone can make an attestation and be added to the seen set, but only once every required attestation has been added to the seen set are the votes of the required attestors counted and the challenge resolved based on the majority of them. I think I'll emit the state of all attestations as an event before clearing it from state so it can be reported to the UI - feedback welcome on format and info that would include. 

things that might need clarification/context: the bug: seemingly we're seeing a challenge in the challengeMap with selectedUserIndex, challengeIndex set to 0 - this challenge is for the pubkey 0x0....0 (which is obviously invalid), chunk 0, with a deadline of 0 blocks. This should not be a possible/valid challenge.

**Comment by jam10o-new** [comment]
would probably be worthwhile to concretely determine what the blockers are for calling something a good "v1" next meeting.

**Comment by ninabreznik** [comment]
Quick short notes:

### Updates
- @joshua-mir  sharing snippet about the challenges process https://gist.github.com/joshua-mir/4ac7207360103bdd79a27cbd9a0d07a1
- @serapath  sharing DatDot spec https://hackmd.io/lnHbg-sgTlaXfkVCcMM_MA?both
  - add Offer attesting
  - add Nominate as friend (Add friend?)
- @RangerMauve  finished Intercept-hypercore-storage https://github.com/RangerMauve/intercept-hypercore-storage
- @ninabreznik  shared first draft of UX concept https://www.draw.io/#LDaDot

### Other
- try to use linter
- contact Dieter (Web3 foundation grants)
- make DatDot dictionary (hosters = dotters?, backers? etc.) => let's then together discuss
- Encoding/decoding math
- Docker
- Dashboard (get in touch with @substack)
